### ISSUE TITLE
不支持处理带透明通道的图片？

### ISSUE THREAD

**Issue by bGlzdGRlcg** [hanFengSan/realcugan-ncnn-webassembly#4]
![image](https://github.com/user-attachments/assets/e72b18c5-681a-4881-b2f8-31811c36dd72)
如图

**Comment by qiuyu303** [comment]
请问怎么解决的呢

**Comment by bGlzdGRlcg** [comment]
> 请问怎么解决的呢 

另找项目 https://github.com/xororz/web-realesrgan
